site_name: pg_graphql
site_description: GraphQL support for Postgresql.

theme:
    name: 'readthedocs'

repo_name: olirice/graphql
repo_url: https://github.com/olirice/pg_graphql

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - Reflection: 'reflection.md'
    - Queries: 'queries.md'
    - Mutations: 'mutations.md'
    - Performance: 'performance.md'
    - How to Contribute: 'contributors.md'

markdown_extensions:
  - codehilite
  - admonition
